SELECT A.AUTHOR_ID, MAX(AUTHOR_NAME), B.CATEGORY, SUM(B.PRICE * S.SALES) TOTAL_SALES
  FROM AUTHOR A
     , BOOK B
     , (SELECT BOOK_ID, SALES
          FROM BOOK_SALES
         WHERE SALES_DATE BETWEEN TO_DATE('20220101', 'YYYYMMDD')
                              AND TO_DATE('20220201', 'YYYYMMDD') - 1/24/60/60
       ) S
 WHERE A.AUTHOR_ID = B.AUTHOR_ID
   AND B.BOOK_ID = S.BOOK_ID
 GROUP BY A.AUTHOR_ID
        , B.CATEGORY
 ORDER BY A.AUTHOR_ID
        , B.CATEGORY DESC