SELECT C.CAR_ID, C.CAR_TYPE, ROUND((C.DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100)) FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS C,
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
WHERE
    C.CAR_TYPE = D.CAR_TYPE
    AND D.DURATION_TYPE LIKE '30일 이상'
    AND C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
        # 22.11.01 ~ 22.11.30 까지 대여 불가한 CAR_ID 리스트
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
        GROUP BY CAR_ID
    )    
    AND (C.DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30) BETWEEN 500000 AND (2000000 - 1)
    
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC