SELECT MONTH, CAR_ID, COUNT(*) AS RECORDS

# 한자리수 렌트 시작일, CAR_ID로 테이블을 구성하여 불러옴
FROM (SELECT MONTH(START_DATE) AS MONTH, CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31') as CAR
      
GROUP BY MONTH, CAR_ID
HAVING CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                 GROUP BY CAR_ID
                 HAVING COUNT(*) >= 5)
ORDER BY MONTH, CAR_ID DESC
      


