SELECT
    A.FOOD_TYPE,
    A.REST_ID,
    A.REST_NAME,
    A.FAVORITES
FROM
    REST_INFO A,
    (
        SELECT REST_ID, FOOD_TYPE, MAX(FAVORITES) FAV
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    ) MAX_FAV
WHERE 
    MAX_FAV.FOOD_TYPE = A.FOOD_TYPE
    AND MAX_FAV.FAV = A.FAVORITES
ORDER BY
    FOOD_TYPE DESC;