SELECT S.YEAR
     , S.MONTH
     , NVL(I.GENDER, 0) AS GENDER
     , COUNT(*) AS USERS
  FROM USER_INFO I
     , (SELECT DISTINCT
               USER_ID
             , EXTRACT(YEAR FROM SALES_DATE) YEAR
             , EXTRACT(MONTH FROM SALES_DATE) MONTH
          FROM ONLINE_SALE
       ) S
 WHERE I.USER_ID = S.USER_ID
   AND I.GENDER IS NOT NULL
 GROUP BY S.YEAR, S.MONTH, I.GENDER
 ORDER BY S.YEAR, S.MONTH, I.GENDER