-- 코드를 입력하세요
SELECT CATEGORY, OT.PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS OT
WHERE PRICE = (SELECT MAX(IT.PRICE)
                FROM FOOD_PRODUCT AS IT
                WHERE OT.CATEGORY = IT.CATEGORY)
    AND (CATEGORY LIKE '식용유'
        OR CATEGORY LIKE '과자'
        OR CATEGORY LIKE '국'
        OR CATEGORY LIKE '김치')
ORDER BY PRICE DESC