SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW R,
    MEMBER_PROFILE M,
    (SELECT MEMBER_ID, COUNT(*) CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC
    LIMIT 1) MOST_ID
WHERE
    R.MEMBER_ID = M.MEMBER_ID
    AND R.MEMBER_ID = MOST_ID.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT
    