SELECT CAR_ID
     , DECODE(MAX(AVAILABILITY), 0, '대여 가능', '대여중') AS AVAILABILITY
  FROM (SELECT CAR_ID
             , CASE WHEN to_date('20221016', 'YYYYMMDD') BETWEEN START_DATE AND END_DATE
                    THEN 1
                    ELSE 0
                END AS AVAILABILITY
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
       ) A
 GROUP BY CAR_ID
 ORDER BY CAR_ID DESC