SELECT FLAVOR
FROM (
    SELECT J.FLAVOR FLAVOR, SUM(J.TOTAL_ORDER + FH.TOTAL_ORDER) TOTAL
    FROM (
        SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) J, FIRST_HALF FH
    WHERE J.FLAVOR = FH.FLAVOR
    GROUP BY J.FLAVOR
) T
ORDER BY TOTAL DESC
LIMIT 3