SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) * PRICE TOTAL_SALES
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
    AND YEAR(O.PRODUCE_DATE) = 2022
    AND MONTH(O.PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID