SELECT B.BOOK_ID BOOK_ID,
    A.AUTHOR_NAME AUTHOR_NAME,
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM BOOK AS B, AUTHOR AS A
WHERE B.CATEGORY LIKE '경제' AND
    B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY B.PUBLISHED_DATE