-- 코드를 입력하세요
SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(SUM(REVIEW_SCORE) / COUNT(*), 2) as SCORE
FROM REST_INFO i, REST_REVIEW r
WHERE i.REST_ID = r.REST_ID
    and i.ADDRESS LIKE '서울%'
GROUP BY i.REST_ID
ORDER BY SCORE desc, i.FAVORITES desc